### ISSUE TITLE
Crash when setting a point on the map yet to be layed out

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-app#54]
Display data on map only after map has been layed out. I.e. move the displayData upstream call only after layout of views are completed.

Crash report:
```
2018-10-18 14:28:35.201 16172-16172/it.geosolutions.savemybike E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.geosolutions.savemybike, PID: 16172
    com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
        at com.google.maps.api.android.lib6.common.n.b(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):11)
        at com.google.maps.api.android.lib6.gmm6.api.a.a(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):175)
        at com.google.maps.api.android.lib6.impl.aa.a(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):3)
        at com.google.maps.api.android.lib6.gmm6.api.a.a(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):44)
        at com.google.maps.api.android.lib6.impl.bc.a(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):369)
        at com.google.android.gms.maps.internal.l.a(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):24)
        at fc.onTransact(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):12)
        at android.os.Binder.transact(Binder.java:604)
        at com.google.android.gms.internal.maps.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzg.moveCamera(Unknown Source:8)
        at com.google.android.gms.maps.GoogleMap.moveCamera(Unknown Source:6)
        at it.geosolutions.savemybike.ui.activity.TrackDetailsActivity.displayData(TrackDetailsActivity.java:221)
        at it.geosolutions.savemybike.ui.activity.TrackDetailsActivity.onMapReady(TrackDetailsActivity.java:177)
        at com.google.android.gms.maps.zzak.zza(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:31)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.transact(Binder.java:604)
        at fb.b(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):20)
        at com.google.android.gms.maps.internal.bg.a(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):5)
        at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@12874027@12.8.74 (040800-204998136):5)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by giohappy** [comment]
As I supposed, onMapReady callback doesn't guarantee
